# Generated by Django 2.1.4 on 2019-01-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('department_id', models.IntegerField(default=0)),
                ('aisle', models.CharField(max_length=100)),
                ('aisle_id', models.IntegerField(default=0)),
                ('product', models.CharField(max_length=100)),
                ('product_id', models.IntegerField(default=0)),
            ],
        ),
    ]
