# Generated by Django 2.1.4 on 2019-01-04 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_auto_20190103_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=200, null=True)),
                ('department_id_vc', models.FloatField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Night',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=200, null=True)),
                ('department_id_vc', models.FloatField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('eval_set', models.CharField(max_length=200, null=True)),
                ('order_number', models.IntegerField(null=True)),
                ('order_dow', models.IntegerField(null=True)),
                ('order_hour_of_day', models.IntegerField(null=True)),
                ('days_since_prior_order', models.FloatField(max_length=200, null=True)),
                ('vip', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prior_reorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eval_set', models.CharField(max_length=200, null=True)),
                ('days_since_prior_order', models.FloatField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_big',
            fields=[
                ('department_id', models.FloatField(max_length=200, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_middle',
            fields=[
                ('aisle_id', models.FloatField(max_length=200, primary_key=True, serialize=False)),
                ('aisle', models.CharField(max_length=200, null=True)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.Product_big')),
            ],
        ),
        migrations.CreateModel(
            name='Product_small',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.FloatField(max_length=200, null=True)),
                ('product_name', models.CharField(max_length=200, null=True)),
                ('aisle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.Product_middle')),
            ],
        ),
        migrations.CreateModel(
            name='Vip_organic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=200, null=True)),
                ('product_name', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vip_reorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eval_set', models.CharField(max_length=200, null=True)),
                ('days_since_prior_order', models.FloatField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveField(
            model_name='product',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='aisle',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='aisle_id',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='department',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='department_id',
            field=models.FloatField(max_length=200, null=True),
        ),
    ]
