# Generated by Django 2.1.4 on 2019-01-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_auto_20190105_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_dow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sat', models.IntegerField(default=0, null=True)),
                ('Sun', models.IntegerField(default=0, null=True)),
                ('Mon', models.IntegerField(default=0, null=True)),
                ('Tues', models.IntegerField(default=0, null=True)),
                ('Wed', models.IntegerField(default=0, null=True)),
                ('Thrs', models.IntegerField(default=0, null=True)),
                ('Fri', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='aisle',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='department',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
