# Generated by Django 2.1.4 on 2019-01-06 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_aisle_list_product_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aisle_list',
            new_name='Product_middle',
        ),
        migrations.RenameModel(
            old_name='Product_list',
            new_name='Product_small',
        ),
    ]
