# Generated by Django 2.1.4 on 2019-01-06 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0009_auto_20190107_0053'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_dow',
            new_name='Orders_dow',
        ),
    ]
