# Generated by Django 2.1.4 on 2019-01-06 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0010_auto_20190107_0056'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders_dow',
            new_name='Order_dow',
        ),
    ]
