# Generated by Django 2.1.4 on 2019-01-06 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0012_auto_20190107_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_small',
            fields=[
                ('product_id', models.FloatField(default=999999, max_length=200, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200, null=True)),
                ('aisle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.Product_middle')),
            ],
        ),
    ]
